services:
  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - 9898:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: invoice_system
  java_app:
    container_name: java_app
    image: invoice-system
    build: .
    ports:
     - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://java_db:5432/invoice_system
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - java_db

  angular-app:
    build: ./angular-app
    depends_on:
      - java_app

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./angular-app/dist/invoice-system-front:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - angular-app
  

