version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: password
      POSTGRES_PASSWORD: invoice_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "9898:5432"

  java-app:
    image: openjdk:17-jdk-alpine
    volumes:
      - ./java_app/app.jar:/app.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/invoice_system
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    entrypoint: ["java", "-jar", "/app.jar"]
    ports:
      - "8080:8080"
    depends_on:
      - db

  angular-app:
    image: nginx:alpine
    volumes:
      - ./angular_app/dist/invoice-system-front:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - java-app

volumes:
  postgres_data:
